---
apiVersion: v1
kind: Service
metadata:
  name: head-svc 
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  type: ClusterIP
  clusterIP: None
#headless service make sure that service DNS is not binded to single clusterIP address ,if we no need to loadbalance the traffic in such situation we need to opt for headless and here clusterIP is not allocated for which kube-proxy will not handle these service