---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: write-container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c","echo Hello kubernetes > /pod-data/index.html;sleep 1d"]
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
    - name: read-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          hostPort: 8080 #hostport binds a node machine port to contianer port so we can access the pod from outside cluster .
      resources:
        requests:
          cpu: 100m 
          memory: 128Mi
        limits:
          cpu: 200m 
          memory: 256Mi
  volumes:
    - name: shared-data
      emptyDir: {}