---
apiVersion: v1
kind: ResourceQuota #using ResourceQuota we can divide resources to Namespaces
metadata:
  name: ecomm-quota 
  namespace: ecomm-project
spec: 
  hard: #hard is of type object used to set hard limits for each named resource
    pods: 10
    configmaps: "20"
    secrets: "10"
    services: "30"
    persistentvolumeclaims: "50"
    limits.memory: "800Mi"
    limits.cpu: "10"